package traffic;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author student
 */
public class MonitoringStation1 extends javax.swing.JFrame
{

    /**
     * Creates new form MonitoringStation1
     */
    public MonitoringStation1()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblMonitoringStation1 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblLanes = new javax.swing.JLabel();
        lblTotalVehicles = new javax.swing.JLabel();
        lblAvgVehicles = new javax.swing.JLabel();
        lblAvgVelocity = new javax.swing.JLabel();
        lblEnterYourReadingsAndClickSubmit = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtLanes = new javax.swing.JTextField();
        txtTotalVehicles = new javax.swing.JTextField();
        txtAvgVehicles = new javax.swing.JTextField();
        txtAvgVelocity = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMonitoringStation1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMonitoringStation1.setText("Monitoring Station 1");
        lblMonitoringStation1.setName(""); // NOI18N

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTime.setText("Time:");

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLocation.setText("Location:");

        lblLanes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLanes.setText("#Lanes");

        lblTotalVehicles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotalVehicles.setText("Total # Vehicles");

        lblAvgVehicles.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAvgVehicles.setText("Avg. #Vehicles");

        lblAvgVelocity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAvgVelocity.setText("Avg. Velocity");

        lblEnterYourReadingsAndClickSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEnterYourReadingsAndClickSubmit.setText("Enter Your Readings And Click Submit");

        btnSubmit.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(lblMonitoringStation1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblEnterYourReadingsAndClickSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLocation)
                            .addComponent(lblTime)
                            .addComponent(lblLanes)
                            .addComponent(lblTotalVehicles)
                            .addComponent(lblAvgVehicles)
                            .addComponent(lblAvgVelocity))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTime)
                            .addComponent(txtLocation)
                            .addComponent(txtLanes)
                            .addComponent(txtTotalVehicles)
                            .addComponent(txtAvgVehicles)
                            .addComponent(txtAvgVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSubmit)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblMonitoringStation1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblEnterYourReadingsAndClickSubmit)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLanes)
                    .addComponent(txtLanes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalVehicles)
                    .addComponent(txtTotalVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvgVehicles)
                    .addComponent(txtAvgVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAvgVelocity)
                    .addComponent(txtAvgVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addContainerGap())
        );

        lblMonitoringStation1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MonitoringStation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MonitoringStation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MonitoringStation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MonitoringStation1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MonitoringStation1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAvgVehicles;
    private javax.swing.JLabel lblAvgVelocity;
    private javax.swing.JLabel lblEnterYourReadingsAndClickSubmit;
    private javax.swing.JLabel lblLanes;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMonitoringStation1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotalVehicles;
    private javax.swing.JTextField txtAvgVehicles;
    private javax.swing.JTextField txtAvgVelocity;
    private javax.swing.JTextField txtLanes;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTotalVehicles;
    // End of variables declaration//GEN-END:variables
}
